# Generated by Django 4.1.6 on 2023-04-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pairing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pairing',
            name='brother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='pairing.brother'),
        ),
    ]
